modeDeclarationGroups:
  - name: Mdg_PowerState
    category: explicitOrder
    initialMode: "OFF"
    onTransitionValue: 255
    modes:
      - name: "OFF"
        value: 0
      - name: "ON"
        value: 1
      - name: "SLEEP"
        value: 1
